stages:
  - validate
  - plan
  - apply

image:
  name: hashicorp/terraform:latest
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

before_script:
  - mkdir -p /creds
  - echo "$SERVICE_ACCOUNT_KEY" | base64 -d > /creds/credentials.json
  - export GOOGLE_APPLICATION_CREDENTIALS="/creds/credentials.json"
  - rm -rf .terraform
  - terraform --version
  - terraform init

validate:
  stage: validate
  script:
    - terraform validate

plan:
  stage: plan
  script:
    - terraform plan
  dependencies:
    - validate

apply:
  stage: apply
  script:
    - terraform init
    - terraform apply -auto-approve
  dependencies:
    - plan
  when: manual

after_script:
  - rm -rf /creds